### ISSUE TITLE
Final group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by c00p75** [c00p75/appointment-app-backend#11]
# Final group capstone: set up your Kanban board

-  [Link to project](https://github.com/users/c00p75/projects/3)

- Number of team members: **4**

> ![Screenshot 2023-07-12 175009](https://github.com/c00p75/appointment-app-backend/assets/78291662/e2a23b97-e57f-41a1-8ba2-917f9995080e)

**Comment by Meltrust** [comment]
Hi @c00p75,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have descriptions, have been assigned, and have fair pointings ✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by maov19** [comment]
Closed, as approved by reviewer.
